language: ruby
rvm:
  - 2.0.0
  - 1.9.3
gemfile:
  - gemfiles/Gemfile-rails.3.2.x
  - Gemfile
notifications:
  email: false
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "PexwWrMM6bkEVPt5b28GGSF5ThaUX5mRgY/8fK3kAXgGolvXoZdF6XZt8zE1\nTbE+AMQLayILXOFRd1bTL537Qf2Y63n6arKH19t9GBBdqZo1ZveVOca0qiSB\n0reSG8sauQXUA95ygEqhWd6VYkDRu1oJpwgsDv47igawbqAOrgE="
